### ISSUE TITLE
What about run npm run start?

### ISSUE THREAD

**Issue by jhzao82** [dzmitROCK/Bootstrap4Press#1]
npm run start

> Bootstrap4Press@1.0.0 start /var/www/html/wordpress/wp-content/themes/Bootstrap4Press
> gulp

[20:24:20] Failed to load external module @babel/register
[20:24:20] Requiring external module babel-register
/var/www/html/wordpress/wp-content/themes/Bootstrap4Press/node_modules/webpack/lib/Compiler.js:11
const {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Module._extensions..js (module.js:417:10)
    at Object.require.extensions.(anonymous function) [as .js] (/var/www/html/wordpress/wp-content/themes/Bootstrap4Press/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/html/wordpress/wp-content/themes/Bootstrap4Press/node_modules/webpack/lib/webpack.js:7:18)
    at Module._compile (module.js:410:26)

npm ERR! Linux 4.15.0-24-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! Bootstrap4Press@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Bootstrap4Press@1.0.0 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Bootstrap4Press package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Bootstrap4Press
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Bootstrap4Press
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/wordpress/wp-content/themes/Bootstrap4Press/npm-debug.log

**Comment by dzmitROCK** [comment]
npm -v && node -v

my environment
6.2.0
v10.6.0

I think you need to update the nodejs and npm
